modLoader = "javafml"
loaderVersion = "[40,)"
license = "GPL v3"
[[mods]]
modId = "ore_tree"
version = "1.0.0"
displayName = "Ore Tree"
logoFile = "logo.png"
credits = "Thanks for PR(s) by holty07"
authors = "Committee Nova, Wugui_sp, Tapio"
description = '''
A mod to bring ore tree to Minecraft
'''
[[dependencies.ore_tree]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"