modLoader="javafml"
loaderVersion="[38,)"
license="GPL v3"
[[mods]]
modId = "ore_tree"
version = "0.2.5.1"
displayName = "Ore Tree"
logoFile = "logo.png"
credits = "Thanks for PR(s) by holty07"
authors = "Team Fractal, Wugui_sp, Tapio"
description='''
A mod to bring ore tree to Minecraft
'''
[[dependencies.ore_tree]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"